[phases.build]
cmds = [
    "pip install -r requirements.txt",
    "python manage.py collectstatic --noinput"
]

[phases.deploy]
cmds = [
    "python manage.py migrate --noinput"
]

[start]
cmd = "python manage.py migrate --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
